[package]
name = "importer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
csv = "1.3.1"
duckdb = { version = "1.1.1", features = ["bundled"] }
rayon = "1.10.0"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
tar = "0.4.43"
zstd = "0.13.2"
