[package]
name = "importer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
csv = "1.3.1"
duckdb = { version = "1.1.1", features = ["bundled"] }
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
